movie_cast = {
    '3G.mp4': {'actor': 'Neil Nitin Mukesh', 'actress': 'Sonal Chauhan'},
    'BANJO.mp4': {'actor': 'Riteish Deshmukh', 'actress': 'Nargis Fakhri'},
    'Chalo Dilli.mp4': {'actor': 'Vinay Pathak', 'actress': 'Lara Dutta'},
    'FILHAAL_SD.mp4': {'actor': 'Sanjay Suri', 'actress': 'Tabu', 'actress2': 'Sushmita Sen'},
    'HUM TUMHARE HAI SANAM.mp4': {'actor': 'Shah Rukh Khan', 'actress': 'Madhuri Dixit', 'actor2': 'Salman Khan'},
    'Kambakth Ishq.mp4': {'actor': 'Akshay Kumar', 'actress': 'Kareena Kapoor'},
    'MR WHITE MR BLACK.mp4': {'actor': 'Suniel Shetty', 'actress': 'Arshad Warsi', 'actress2': 'Mahima Chaudhry'},
    'PAAGALPAN_SD.mp4': {'actor': 'Karan Nath', 'actress': 'Arti Agarwal'},
    'SARKAR 3.mp4': {'actor': 'Amitabh Bachchan', 'actor2': 'Jackie Shroff', 'actress': 'Yami Gautam'},
    'Table No 21.mp4': {'actor': 'Paresh Rawal', 'actress': 'Tina Desai', 'actor2': 'Rajeev Khandelwal'},
    'YUDH EK JUNG_DICTATOR_2016_HINDI.mp4': {'actor': 'Nandamuri Balakrishna', 'actress': 'Anjali', 'actress2': 'Sonal Chauhan'}, # Assuming this is the Hindi dubbed version of "Dictator" (2016)
    'AA DEKHEN ZARA.mp4': {'actor': 'Neil Nitin Mukesh', 'actress': 'Bipasha Basu'},
    'BAWRI CHHORI.mp4': {'actor': None, 'actress': 'Rumana Molla', 'actress2': 'Aahana Kumra', 'actress3': 'Niki Aneja Walia'},
    'Chintuji.mp4': {'actor': 'Rishi Kapoor', 'actress': 'Kulraj Randhawa'},
    'GANDHI MY FATHER.mp4': {'actor': 'Darshan Jariwala', 'actress': 'Bhumika Chawla'},
    'Haathi Mere Saathi_2021.mp4': {'actor': 'Rana Daggubati', 'actress': 'Pulkit Samrat', 'actress2': 'Shriya Pilgaonkar', 'actress3': 'Zoya Hussain'},
    'Khiladi786.mp4': {'actor': 'Akshay Kumar', 'actress': 'Asin'},
    'MUKKABAAZ.mp4': {'actor': 'Vineet Kumar Singh', 'actress': 'Zoya Hussain'},
    'PARTNER.mp4': {'actor': 'Salman Khan', 'actress': 'Lara Dutta', 'actor2': 'Govinda', 'actress2': 'Katrina Kaif'},
    'SAUDA.mp4': {'actor': 'Vikas Bhardwaj', 'actress': 'Soma Dey'}, # Information scarce, this is based on limited search
    'Tanu Weds Manu Return.mp4': {'actor': 'R. Madhavan', 'actress': 'Kangana Ranaut'},
    'ANWAR KA AJAB KISSA AKA SNIFFER.mp4': {'actor': 'Nawazuddin Siddiqui', 'actress': 'Ananya Chatterjee'},
    'BENNY AND BABLOO.mp4': {'actor': 'Kay Kay Menon', 'actress': 'Riya Sen', 'actress2': 'Shweta Tiwari'},
    'DRONA.mp4': {'actor': 'Abhishek Bachchan', 'actress': 'Priyanka Chopra'},
    'GANG.mp4': {'actor': 'Nana Patekar', 'actress': 'Juhi Chawla'},
    'Happy Bhag Jayegi.mp4': {'actor': 'Abhay Deol', 'actress': 'Diana Penty', 'actor2': 'Jimmy Sheirgill'},
    'Ki & Ka.mp4': {'actor': 'Arjun Kapoor', 'actress': 'Kareena Kapoor Khan'},
    'Manmarziyaan.mp4': {'actor': 'Vicky Kaushal', 'actress': 'Taapsee Pannu', 'actor2': 'Abhishek Bachchan'},
    'PHOBIA.mp4': {'actor': 'Radhika Apte', 'actress': None}, # Radhika Apte is the central character
    'SHAMITABH.mp4': {'actor': 'Dhanush', 'actress': 'Akshara Haasan', 'actor2': 'Amitabh Bachchan'},
    'Tanu Weds Manu.mp4': {'actor': 'R. Madhavan', 'actress': 'Kangana Ranaut'},
    'ASTITVA.mp4': {'actor': 'Sachin Khedekar', 'actress': 'Tabu'},
    'BHOOT RETURNS.mp4': {'actor': 'J. D. Chakravarthy', 'actress': 'Manisha Koirala'},
    'DUS KAHANIYAAN.mp4': {'actor': 'Sanjay Dutt', 'actress': 'Tabu', 'multiple_cast': True}, # Anthology film with many actors
    'Goliyon Ki Raasleela Ram-Leela.mp4': {'actor': 'Ranveer Singh', 'actress': 'Deepika Padukone'},
    'Happy Ending.mp4': {'actor': 'Saif Ali Khan', 'actress': 'Ileana D\'Cruz'},
    'Kiss Kis Ko.mp4': {'actor': 'Kapil Sharma', 'actress': 'Elli AvrRam', 'actress2': 'Simran Kaur Mundi'},
    'Munna Michael.mp4': {'actor': 'Tiger Shroff', 'actress': 'Nidhhi Agerwal'},
    'PRAHAR.mp4': {'actor': 'Nana Patekar', 'actress': 'Madhu Sapre'},
    'SNIFF.mp4': {'actor': 'Sunny Gill', 'actress': 'Khushmeet Gill'}, # Child actors as leads
    'U Me Aur Hum.mp4': {'actor': 'Ajay Devgn', 'actress': 'Kajol'},
    'AUR PYAR HO GAYA.mp4': {'actor': 'Bobby Deol', 'actress': 'Aishwarya Rai Bachchan'},
    'BOL.mp4': {'actor': 'Atif Aslam', 'actress': 'Humaima Malik', 'actress2': 'Mahira Khan'},
    'Daud.mp4': {'actor': 'Sanjay Dutt', 'actress': 'Urmila Matondkar'},
    'Golmaal 3.mp4': {'actor': 'Ajay Devgn', 'actress': 'Kareena Kapoor Khan', 'actor2': 'Arshad Warsi', 'actor3': 'Tusshar Kapoor', 'actor4': 'Shreyas Talpade'},
    'Happy Phir Bhag Jayegi.mp4': {'actor': 'Sonakshi Sinha', 'actress': 'Diana Penty', 'actor2': 'Jimmy Sheirgill', 'actor3': 'Jassie Gill'},
    'LAJJA_SD.mp4': {'actor': 'Jackie Shroff', 'actress': 'Manisha Koirala', 'actress2': 'Mahima Chaudhry', 'actress3': 'Madhuri Dixit', 'actress4': 'Rekha'},
    'NANHE JAISALMER.mp4': {'actor': 'Dwij Yadav', 'actress': 'Bobby Deol'}, # Bobby Deol plays himself, Dwij Yadav is the child lead
    'Paramaatma.mp4': {'actor': 'Mithun Chakraborty', 'actress': 'Juhi Chawla'},
    'SWITCHH.mp4': {'actor': 'Ruslaan Mumtaz', 'actress': 'Nysa Devgan'}, # Nysa Devgan has been mentioned, but film is yet to release
    'VAADA RAHA.mp4': {'actor': 'Bobby Deol', 'actress': 'Kangana Ranaut', 'actor2': 'Dwij Yadav'},
    'Action Jackson.mp4': {'actor': 'Ajay Devgn', 'actress': 'Sonakshi Sinha', 'actress2': 'Yami Gautam'},
    'Badlapur.mp4': {'actor': 'Varun Dhawan', 'actress': 'Yami Gautam', 'actor2': 'Nawazuddin Siddiqui'},
    'Desi Boyz.mp4': {'actor': 'Akshay Kumar', 'actress': 'John Abraham', 'actress2': 'Deepika Padukone', 'actress3': 'Chitrangada Singh'},
    'HAAL-E-DIL.mp4': {'actor': 'Adhyayan Suman', 'actress': 'Amrita Rao', 'actress2': 'Nakuul Mehta'},
    'Housefull 3.mp4': {'actor': 'Akshay Kumar', 'actress': 'Jacqueline Fernandez', 'actor2': 'Riteish Deshmukh', 'actor3': 'Abhishek Bachchan', 'actress2': 'Nargis Fakhri', 'actress3': 'Lisa Haydon'},
    'Lal Kaptaan.mp4': {'actor': 'Saif Ali Khan', 'actress': 'Zoya Hussain', 'actress2': 'Manav Vij', 'actress3': 'Simone Singh'},
    'NEW DELHI.mp4': {'actor': 'Jagathy Sreekumar', 'actress': 'Sumalatha', 'actor2': 'Mammootty'}, # Assuming the 1987 Malayalam film New Delhi.
    'Purani Jeans.mp4': {'actor': 'Tanuj Virwani', 'actress': 'Izabelle Leite', 'actor2': 'Aditya Seal'},
    'Salaam E Ishq.mp4': {'actor': 'Salman Khan', 'actress': 'Priyanka Chopra', 'multiple_cast': True}, # Ensemble cast
    'VIGHNAHARTA SHREE SIDDHIVINAYAK.mp4': {'actor': None, 'actress': None}, # Limited information found
    'Agent Vinod.mp4': {'actor': 'Saif Ali Khan', 'actress': 'Kareena Kapoor Khan'},
    'Bajirao Mastani.mp4': {'actor': 'Ranveer Singh', 'actress': 'Deepika Padukone', 'actress2': 'Priyanka Chopra'},
    'Devdas.mp4': {'actor': 'Shah Rukh Khan', 'actress': 'Aishwarya Rai Bachchan', 'actress2': 'Madhuri Dixit'},
    'HALAHAL-MRITYULOK.mp4': {'actor': 'Sachin Khedekar', 'actress': 'Barun Sobti', 'actress2': 'Palak Purswani'},
    'Housefull.mp4': {'actor': 'Akshay Kumar', 'actress': 'Deepika Padukone', 'actress2': 'Lara Dutta', 'actress3': 'Jiah Khan', 'actor2': 'Riteish Deshmukh', 'actor3': 'Fardeen Khan'},
    'London Dreams.mp4': {'actor': 'Salman Khan', 'actress': 'Ajay Devgn', 'actress2': 'Asin'},
    'NH 10.mp4': {'actor': 'Neil Bhoopalam', 'actress': 'Anushka Sharma'},
    'Ra One.mp4': {'actor': 'Shah Rukh Khan', 'actress': 'Kareena Kapoor Khan'},
    'Shirin Farhad Ki Toh Nikal Padi.mp4': {'actor': 'Boman Irani', 'actress': 'Farah Khan'},
    'Vicky Donor.mp4': {'actor': 'Ayushmann Khurrana', 'actress': 'Yami Gautam'},
    'Aligarh.mp4': {'actor': 'Manoj Bajpayee', 'actress': 'Rajkummar Rao'},
    'Buddha Mar Gaya.mp4': {'actor': 'Anupam Kher', 'actress': 'Mona Ambegaonkar', 'actor2': 'Paresh Rawal'},
    'Dhoom Dhadakka.mp4': {'actor': 'Sameer Dattani', 'actress': 'Celina Jaitly'},
    'HAPPY ENDING.mp4': {'actor': 'Saif Ali Khan', 'actress': 'Ileana D\'Cruz'},
    'Hum dil De Chuke Sanam.mp4': {'actor': 'Salman Khan', 'actress': 'Aishwarya Rai Bachchan', 'actor2': 'Ajay Devgn'},
    'Love Aaj Kal.mp4': {'actor': 'Saif Ali Khan', 'actress': 'Deepika Padukone'},
    'NO SMOKING.mp4': {'actor': 'John Abraham', 'actress': 'Ayesha Takia', 'actress2': 'Anurag Kashyap'},
    'Ranjhana.mp4': {'actor': 'Dhanush', 'actress': 'Sonam Kapoor'},
    'Subh Mangal Savdhan.mp4': {'actor': 'Ayushmann Khurrana', 'actress': 'Bhumi Pednekar'},
    'WEDDING PULLAV.mp4': {'actor': 'Diganth Manchale', 'actress': 'Anushka Ranjan', 'actress2': 'Karan Grover'},
    'Anjana Anjani.mp4': {'actor': 'Ranbir Kapoor', 'actress': 'Priyanka Chopra'},
    'Chaahat – Ek Nasha.mp4': {'actor': 'Aryan Vaid', 'actress': 'Manisha Koirala', 'actress2': 'Preeti Jhangiani'},
    'Dishoom.mp4': {'actor': 'John Abraham', 'actress': 'Varun Dhawan', 'actress2': 'Jacqueline Fernandez'},
    'HEY RAM.mp4': {'actor': 'Kamal Haasan', 'actress': 'Rani Mukerji', 'actress2': 'Vasundhara Das'},
    'JAMUN.mp4': {'actor': 'Manav Kaul', 'actress': 'Shweta Tripathi'},
    'MERI NIMMO.mp4': {'actor': 'Anjali Patil', 'actress': 'Karan Dave'},
    'NYAY ANYAY.mp4': {'actor': 'Jitendra', 'actress': 'Jaya Prada'},
    'Rockstar.mp4': {'actor': 'Ranbir Kapoor', 'actress': 'Nargis Fakhri'},
    'Sunday.mp4': {'actor': 'Ajay Devgn', 'actress': 'Ayesha Takia'},
    'Warning.mp4': {'actor': 'Santosh Barmola', 'actress': 'Suzana Rodrigues', 'actor2': 'Manjari Fadnnis'},
    'BAJATE RAHO.mp4': {'actor': 'Tusshar Kapoor', 'actress': 'Vishakha Singh', 'actor2': 'Ranvir Shorey', 'actor3': 'Vinay Pathak'},
    'Chakravyuh.mp4': {'actor': 'Arjun Rampal', 'actress': 'Esha Gupta', 'actor2': 'Abhay Deol', 'actor3': 'Manoj Bajpayee'},
    'English Vinglish.mp4': {'actor': 'Adil Hussain', 'actress': 'Sridevi'},
    'HIJACK.mp4': {'actor': 'Shiney Ahuja', 'actress': 'Esha Deol'},
    'KANOON KI AWAAZ.mp4': {'actor': 'Vinod Khanna', 'actress': 'Shabana Azmi'},
    'MONEY HAI TOH HONEY HAI.mp4': {'actor': 'Govinda', 'actress': 'Celina Jaitly', 'actress2': 'Hansika Motwani'},
    'Omkara.mp4': {'actor': 'Ajay Devgn', 'actress': 'Kareena Kapoor Khan', 'actor2': 'Saif Ali Khan', 'actor3': 'Vivek Oberoi'},
    'SAB KUSHAL MANGAL.mp4': {'actor': 'Priyaank Sharma', 'actress': 'Riva Arora', 'actor2': 'Akshaye Khanna'},
    'TERI MERI KAHANI.mp4': {'actor': 'Shahid Kapoor', 'actress': 'Priyanka Chopra'},
    'YEH RAAT PHIR NA AAYEGI.mp4': {'actor': 'Prithvi', 'actress': 'Arpita Mukherjee'}
}





